routes/web.php
<?php

Auth::routes();

// Dashboard
Route::get('dashboard', function (){
	return view('dashboard.index');
})->middleware('auth')->name('dashboard');

//  Dashboard posts
Route::resource('dashboard/posts', 'PostController');

// Dashboard user
Route::get('dashboard/user/{user}', 'UserController@show')->name('user.show');
Route::get('dashboard/user/{user}/edit', 'UserController@edit')->name('user.edit');
Route::put('dashboard/user/{user}', 'UserController@update')->name('user.update');

// Pages
Route::get('/', 'PageController@home')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
		'title', 'body', 'image'
	];

    /**
     * Get the post's image path
     * @return string
     */
    public function getImageAttribute()
    {
        $filename = $this->attributes['image'];

        if (! $filename) {
            return 'images/post/no-image.jpg';
        }

        return 'storage/images/post/'.$filename;
    }

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    /**
     * Store post image
     * @param  $request
     * @return string|null
     */
    public function storeImage($request)
    {
        if ($request->hasFile('image')) {
            $request->file('image')->store('images/post/', 'public');

            return $request->file('image')->hashName();
        }

        return null;
    }

    /**
     * Update post image
     * @param  $request
     * @return string|null
     */
    public function updateImage($request)
    {
        $filename = $this->attributes['image'];

        if ($request->hasFile('image')) {
            if ($filename) {
                $this->deleteImage();
                return $this->storeImage($request);
            }
            return $this->storeImage($request);
        }

        return $filename;
    }

    /**
     * Delete post image
     * @return bool
     */
    public function deleteImage()
    {
        $filename = $this->attributes['image'];

        if ($filename) {
            Storage::delete('public/images/post/'.$filename);

            return true;
        }

        return false;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Support\Facades\Storage;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'avatar', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get the user's avatar path
     * @return string
     */
    public function getAvatarAttribute()
    {
        if (! $this->attributes['avatar']) {
            return 'images/user/default-avatar.jpg';
        }

        return 'storage/images/user/avatar/'.$this->attributes['avatar'];
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     * Publish a new post
     * @param  Post   $post
     * @return Post
     */
    public function publish(Post $post)
    {
        return $this->posts()->save($post);
    }

    /**
     * Change user avatar
     * @param  $request
     * @return bool
     */
    public function updateAvatar($request)
    {
        $filename = $this->attributes['avatar'];

        if ($request->hasFile('avatar')) {
            if ($filename) {
                Storage::delete('public/images/user/avatar/'.$filename);
            }

            $request->file('avatar')->store('images/user/avatar/', 'public');

            $this->avatar = $request->file('avatar')->hashName();
            return $this->save();
        }

        return $filename;
    }
}

app/helpers.php
<?php

function set_active($path, $active = 'active')
{
	return Request::is($path) ? $active : '';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PageController extends Controller
{
    public function home()
    {
    	return view('pages.home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Http\Requests\BlogPostRequest;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show all posts.
     *
     * @return Response
     */
    public function index()
    {
        $posts = Post::where('user_id', auth()->id())->latest()->paginate(10);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new post.
     *
     * @return Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a new post.
     *
     * @param  BlogPostRequest  $request
     * @param  Post $post
     * @return Response
     */
    public function store(BlogPostRequest $request, Post $post)
    {
        $filename = $post->storeImage($request);

        auth()->user()->publish(
            new Post([
                'title' => $request->title,
                'body' => $request->body,
                'image' => $filename
            ])
        );

        return redirect('dashboard/posts')->with(
            'message', 'Your post has now been published.'
        );
    }

    /**
     * Display the post.
     *
     * @param  Post   $post
     * @return Response
     */
    public function show(Post $post)
    {
        return view('posts.single', compact('post'));
    }

    /**
     * Show the form for editing the post.
     *
     * @param  Post  $post
     * @return Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the post.
     *
     * @param  BlogPostRequest  $request
     * @param  Post $post
     * @return Response
     */
    public function update(BlogPostRequest $request, Post $post)
    {
        $filename = $post->updateImage($request);

        $post->update([
            'title' => $request->title,
            'body' => $request->body,
            'image' => $filename
        ]);

        return redirect('dashboard/posts')->with(
            'message', 'Your post has been updated.'
        );
    }

    /**
     * Remove the post.
     *
     * @param  Post $post
     * @return Response
     */
    public function destroy(Post $post)
    {
        $post->deleteImage();
        $post->delete();

        return redirect('dashboard/posts')->with(
            'message', 'Your post has been deleted.'
        );
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserRequest;

class UserController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display the user info
	 * @param  User   $user
	 * @return Response
	 */
    public function show(User $user)
    {
    	return view('user.profile', compact('user'));
    }

    /**
     * Show the form for editing user info
     * @param  User   $user
     * @return Response
     */
    public function edit(User $user)
    {
    	return view('user.edit', compact('user'));
    }

    /**
     * Update the user info
     * @param  UserRequest $request
     * @param  User        $user   
     * @return bool            
     */
    public function update(UserRequest $request, User $user)
    {
        $user->updateAvatar($request);

        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

    	return redirect()->route('user.show', ['id' => $user->id])->with(
    		'message', 'User profile has been updated.'
    	);
    }
}

resources/views/blog/sidebar.blade.php
@section('sidebar')
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title">Sidebar (ToDo)</h3>
        </div>
        <ul class="list-group">
        	<li class="list-group-item">Search</li>
        	<li class="list-group-item">About</li>
        	<li class="list-group-item">Popular posts</li>
        	<li class="list-group-item">Categories</li>
        	<li class="list-group-item">Newsletter</li>
        </ul>
    </div>
@show

resources/views/dashboard/index.blade.php
@extends('dashboard.master')

@section('body')
	<h2 class="page-header">Dashboard</h2>
@endsection

resources/views/dashboard/master.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @include('dashboard.nav')
            </div>
            <div class="col-md-10">
                <div class="dash-body">
                    @yield('body')
                </div>
                    
                @yield('paginate')
            </div>

            @include('elements.flash-message')
        </div>
    </div>
@endsection

resources/views/dashboard/nav.blade.php
<div class="dash-nav-wrapper">
    <div class="dash-nav-user">
        <img src="{{ asset(auth()->user()->avatar) }}" class="img-responsive">
        <p class="dash-nav-user-info">{{ auth()->user()->name }}</p>
    </div>
    <div class="dash-nav">
        <ul class="nav nav-pills nav-stacked navbar-default">
            <li>
                <a href="{{ route('dashboard') }}" class="{{ set_active('dashboard') }}">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Dashboard
                </a>
            </li>
            <li>
                <a href="{{ route('user.show', ['id' => auth()->id()]) }}" class="{{ set_active('dashboard/user/' . auth()->user()->id) }}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> User
                </a>
          	</li>
            <li>
                <a href="{{ route('posts.index') }}" class="{{ set_active('dashboard/posts') }}">
                    <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Posts
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/elements/errors.blade.php
@if(count($errors) > 0)
	<div>
		<ul class="list-group alert-danger">
			@foreach($errors->all() as $error)
				<li class="list-group-item">{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

resources/views/elements/flash-message.blade.php
@if ($flash = session('message'))
    <div id="flash" class="popover bottom flash-message">
    	<div class="arrow"></div>
    	<h3 class="popover-title alert-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Success</h3>
    	<div class="popover-content">
    		<p>{{ $flash }}</p>
    	</div>
    </div>
@endif

resources/views/elements/post-info.blade.php
<ul class="list-inline">
	<li class="list-inline-item">
		<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
		<span>{{ $post->created_at->diffForHumans() }}</span>
	</li>
	<li class="list-inline-item">
		<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
		<span><em>by</em> {{ $post->user->name }}</span>
	</li>
	<li class="list-inline-item">
		<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
		<span>Category</span>
	</li>
</ul>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
    <link href="/css/app.css" rel="stylesheet">
    <title>{{ config('app.name') }}@yield('title')</title>
    <script>
        window.Laravel =  <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    @include('layouts.header')

    @yield('content')

    @include('layouts.footer')

    <script src="/js/app.js"></script>
    <script>
        var loadFile = function(event) {
            var output = document.getElementById('image');
            output.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
	<div class="container">
		<p class="copy text-center">Copyright &copy {{ Carbon\Carbon::now()->year }} {{ config('app.name')}} All Rights Reserved</p>
	</div>
</footer>

resources/views/layouts/header.blade.php
<header>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ route('home') }}">
                    {{ config('app.name') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="/dashboard">Dashboard</a>
                                </li>
                                <li>
                                    <a href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
</header>

resources/views/pages/home.blade.php
@extends('layouts.app')

@section('content')
	<h1 class="text-primary text-center">Home page</h1>
@endsection

resources/views/posts/create.blade.php
@extends('dashboard.master')

@section('body')
<div class="row">
	<form action="{{ route('posts.store') }}" method="POST" role="form" enctype="multipart/form-data" class="col-md-12 form-horizontal">
		{{ csrf_field() }}
		
		<legend>Create a new post.</legend>
		
		<div class="col-md-8">
			<div class="form-group">
				<label for="post-title">Title:</label>
				<input type="text" id="post-title" class="form-control" name="title" value="{{ old('title') }}" required>
			</div>
			<div class="form-group">
				<label for="post-body">Body:</label>
					<textarea name="body" id="post-body" class="form-control" rows="5" required>{{ old('body') }}</textarea>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Publish</button>
			</div>
			<div class="form-group">
				@include('elements.errors')
			</div>
		</div>
		
		<div class="col-md-3 col-md-offset-1">
			<div class="form-group">
				<label for="image">Image:</label>
		        <img src="" class="img-responsive" id="image">
		        <hr>
				<input type="file" name="image" onchange="loadFile(event)">	
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('dashboard.master')

@section('body')
	<div class="row">
		<form action="{{ route('posts.update', ['id' => $post->id]) }}" method="POST" role="form" enctype="multipart/form-data"  class="col-md-12 form-horizontal" id="edit-post">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			
			<legend>Update post.</legend>

			<div class="col-md-8">
				<div class="form-group">
					<label for="post-title">Title:</label>
					<input type="text" id="post-title" class="form-control" name="title" value="{{ $post->title }}" required>
				</div>
				<div class="form-group">
					<label for="post-body">Body:</label>
					<textarea name="body" id="post-body" class="form-control" rows="5" required>{{ $post->body }}</textarea>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary">Update</button> 
				</div>
				<div class="form-group">
					@include('elements.errors')
				</div>
			</div>

			<div class="col-md-3 col-md-offset-1">
				<div class="col-md-12">
					<div class="form-group">
						<label for="image">Image:</label>
						<img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-responsive" id="image">
					    
					    <hr>
						<input type="file" name="image" onchange="loadFile(event)">
					</div>
				</div>
			</div>
		</form>
	</div>
@endsection

resources/views/posts/index.blade.php
@extends('dashboard.master')

@section('body')
	<div class="table-responsive">
		<h2 class="page-header">All posts<a href="{{ route('posts.create') }}" class="btn btn-primary pull-right">
			<span class="glyphicon glyphicon-send"></span> Create new post
		</a></h2>
		<table class="table table-condensed">
			<thead>
				<th>#</th>
				<th>Title</th>
				<th>Image</th>
				<th>Body</th>
				<th>Created</th>
				<th>Updated</th>
				<th>Action</th>
			</thead>
			<tbody>
				@foreach($posts as $post)
				<tr>
					<td>{{ $post->id }}</td>
					<td>{{ $post->title }}</td>
					<td>
						<img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-circle" width="100" height="100">
					</td>
					<td>{{ str_limit($post->body, 255) }}</td>
					<td>{{ $post->created_at->format('jS F Y, H:i:s') }}</td>
					<td>{{ $post->updated_at->format('jS F Y, H:i:s') }}</td>
					<td width="250">
						<div class="btn-group">
							<a href="{{  route('posts.show', ['id' => $post->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> View</a>

							<a href="{{  route('posts.edit', ['id' => $post->id]) }}" class="btn btn-primary"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit</a>

							<a class="btn btn-danger" data-href="{{  route('posts.destroy', ['id' => $post->id]) }}" data-toggle="modal" data-target="#confirm-delete-{{ $post->id }}"><span class="glyphicon glyphicon-fire"></span> Delete</a>
						</div>

						<div class="modal fade" id="confirm-delete-{{ $post->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						    <div class="modal-dialog">
						        <div class="modal-content">
						            <div class="modal-header">
						                <b>Are youre sure to delete this post?</b>
						            </div>
						            <div class="modal-body">
					                	<span>Post: <a href="{{  route('posts.show', ['id' => $post->id]) }}"><b>{{ $post->title }}</b></a></span>
					            	</div>
						            <div class="modal-footer">
						                <form action="{{  route('posts.destroy', ['id' => $post->id]) }}" method="POST">
											{{ method_field('delete') }}
											{{ csrf_field() }}
											
						                	<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						                	<button type="submit" class="btn btn-danger" data-href="{{  route('posts.destroy', ['id' => $post->id]) }}" data-toggle="modal" data-target="#confirm-delete">Delete</button>
										</form>
						            </div>
						        </div>
						    </div>
						</div>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
@endsection

@section('paginate')
	<div class="row">
		<div class="col-md-12">
			{{ $posts->links() }}
		</div>
	</div>
@endsection

resources/views/posts/single.blade.php
@extends('dashboard.master')

@section('body')
	<div class="row">
		<div class="col-md-12">
			<h1 class="post-title">{{ $post->title }}</h1>
			@include('elements.post-info')
		</div>
		<div class="col-md-4">
			<img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-responsive">
		</div>
		<div class="col-md-8">
			<p>{!! nl2br(e($post->body)) !!}</p>
		</div>
	</div>
@endsection

resources/views/user/edit.blade.php
@extends('dashboard.master')

@section('body')
	<div class="row">
		<form action="{{ route('user.update', ['id' => $user->id]) }}" method="POST" enctype="multipart/form-data" class="col-md-12 form-horizontal" role="form">
			{{ method_field('PUT') }}
			{{ csrf_field() }}

			<legend>Edit user profile</legend>
		
			<div class="col-md-3">
				<div class="form-group">
					<label for="post-thumbnail">Avatar:</label>
					<img src="{{ asset($user->avatar) }}" class="img-responsive thumbnail" id="image" width="350">
				    <hr>
					<input type="file" name="avatar" onchange="loadFile(event)">	
				</div>
			</div>
			<div class="col-md-9">
				<div class="form-group">
					<label for="username">Username:</label>
					<input type="text" name="name" class="form-control" id="username" value="{{ $user->name }}">
				</div>

				<div class="form-group">
					<label for="email">User email:</label>
					<input type="email" name="email" class="form-control" id="userEmail" value="{{ $user->email }}">
				</div>

				<div class="form-group">
					<label for="password">Password:</label>
					<input type="password" name="password" class="form-control" id="userEmail" value="{{ $user->password }}">
				</div>

				<div class="form-group">
					<label for="password_confirmation">Password confirm:</label>
					<input type="password" name="password_confirmation" class="form-control" id="userEmail" value="{{ $user->password }}">
				</div>
			</div>

			<div class="col-md-12">
				<div class="form-group">
					<button type="submit" class="btn btn-primary">Update</button>
				</div>
				
				<div class="form-group">
					@include('elements.errors')
				</div>
			</div>
		</form>
	</div>
@endsection

resources/views/user/profile.blade.php
@extends('dashboard.master')

@section('body')
	<h2>User info</h2>
	<div class="table-responsive">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Avatar</th>
					<th>Username</th>
					<th>Email</th>
					<th>Posts</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
					<img src="{{ asset($user->avatar) }}" class="img-rounded" width="100" height="100">
					</td>
					<td>{{ $user->name }}</td>
					<td>{{ $user->email }}</td>
					<td>Posts count</td>
				</tr>
			</tbody>
		</table>
	</div>
	<a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-primary">Edit profile</a>
@endsection